version: '3'

services:
  frontend:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    # depends_on:
      # - backend
  backend:
    ports:
      - "8000:8000"
    build:
      context: ./server
      dockerfile: Dockerfile