version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
  backend:
    ports:
      - "8000:8000"
    build:
      context: .
      dockerfile: Dockerfile.backend