FROM node:16-alpine AS build-frontend

WORKDIR /app

COPY ./frontend/package.json ./
COPY ./frontend/package-lock.json ./
RUN npm install

COPY ./frontend .
RUN npm run build

FROM nginx:stable-alpine

COPY --from=build-frontend /app/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]