[build]
target = "index.html"
dist = "../dist"
release = false
open = true

# [[proxy]]
# backend = "http://localhost:8000/"

[watch]
watch = []
ignore = []

[clean]
dist = "../dist"
cargo = false

# [[hooks]]
# stage = "pre_build"
# command = "nu"
# command_arguments = [
#     "-c",
#     "tailwindcss -i ./css/input.css -o ./css/output.css",
# ]

# [[hooks]]
# stage = "post_build"
# command = "cargo"
# command_arguments = ["run"]
